# we use this file to setup the CI/CD. Cloud build has a number of tools 
# to setup
#  we need ot create a tigger for this. Something that will execute this 
steps:
# Build Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/node-web-app:$COMMIT_SHA', '.']


# Docker Push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/node-web-app:$COMMIT_SHA']


- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/mydeployment', 'mynode=gcr.io/sit323-23t1-rizvi-690fec0/node-web-app:$COMMIT_SHA']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=hello-cluster'

